import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Navbar from '../components/navbar'
import Main from '../components/main'
import Footer from '../components/footer'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Vote</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar/>
      <Main/>
      <Footer/>
    </div>
  )
}
